first_name_only = false
show_receipts = true
bell = false
colored_messages = true
default_keybindings = true

[notifications]
enabled = true
show_message_text = false
show_message_chat = true
show_reactions = true
mute_reactions_bell = false

[user]
display_name = "Indy"

[keybindings]
