first_name_only = false
show_receipts = true
bell = true
colored_messages = true
default_keybindings = true

[notifications]
enabled = false
show_message_text = true
show_message_chat = true
show_reactions = true
mute_reactions_bell = false

[user]
display_name = "Indy"

[keybindings]
